zick_zack:
    pos0:
        x: 0.04
        y: 0.03
    pos1:
        x: 0.0
        y: 0.09
    pos2:
        x: 0.04
        y: 0.15
    pos3:
        x: 0.0
        y: 0.21
    pos4:
        x: -0.03
        y: 0.0
    pos5:
        x: -0.09
        y: 0.04
    pos6:
        x: -0.15
        y: 0.0
    pos7:
        x: -0.21
        y: 0.04
