/* Auto-generated by genmsg_cpp for file /home/youbot/ros_workspace/youbot_manipulation_vision/msg/RotatedRect.msg */
#ifndef YOUBOT_MANIPULATION_VISION_MESSAGE_ROTATEDRECT_H
#define YOUBOT_MANIPULATION_VISION_MESSAGE_ROTATEDRECT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "geometry_msgs/Point.h"

namespace youbot_manipulation_vision
{
template <class ContainerAllocator>
struct RotatedRect_ {
  typedef RotatedRect_<ContainerAllocator> Type;

  RotatedRect_()
  : centerPoint()
  , width(0.0)
  , height(0.0)
  , angle(0.0)
  {
  }

  RotatedRect_(const ContainerAllocator& _alloc)
  : centerPoint(_alloc)
  , width(0.0)
  , height(0.0)
  , angle(0.0)
  {
  }

  typedef  ::geometry_msgs::Point_<ContainerAllocator>  _centerPoint_type;
   ::geometry_msgs::Point_<ContainerAllocator>  centerPoint;

  typedef double _width_type;
  double width;

  typedef double _height_type;
  double height;

  typedef double _angle_type;
  double angle;


  typedef boost::shared_ptr< ::youbot_manipulation_vision::RotatedRect_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::youbot_manipulation_vision::RotatedRect_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct RotatedRect
typedef  ::youbot_manipulation_vision::RotatedRect_<std::allocator<void> > RotatedRect;

typedef boost::shared_ptr< ::youbot_manipulation_vision::RotatedRect> RotatedRectPtr;
typedef boost::shared_ptr< ::youbot_manipulation_vision::RotatedRect const> RotatedRectConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::youbot_manipulation_vision::RotatedRect_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::youbot_manipulation_vision::RotatedRect_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace youbot_manipulation_vision

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::youbot_manipulation_vision::RotatedRect_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::youbot_manipulation_vision::RotatedRect_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::youbot_manipulation_vision::RotatedRect_<ContainerAllocator> > {
  static const char* value() 
  {
    return "85ead10cf1031b0f418b5071f7763172";
  }

  static const char* value(const  ::youbot_manipulation_vision::RotatedRect_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x85ead10cf1031b0fULL;
  static const uint64_t static_value2 = 0x418b5071f7763172ULL;
};

template<class ContainerAllocator>
struct DataType< ::youbot_manipulation_vision::RotatedRect_<ContainerAllocator> > {
  static const char* value() 
  {
    return "youbot_manipulation_vision/RotatedRect";
  }

  static const char* value(const  ::youbot_manipulation_vision::RotatedRect_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::youbot_manipulation_vision::RotatedRect_<ContainerAllocator> > {
  static const char* value() 
  {
    return "#Center of the rotated rectangle\n\
geometry_msgs/Point centerPoint\n\
\n\
#The width of the rotated rectangle\n\
float64 width\n\
#The height of the rotated rectangle\n\
float64 height\n\
\n\
#The angle of the rotated rectangle\n\
float64 angle\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
";
  }

  static const char* value(const  ::youbot_manipulation_vision::RotatedRect_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::youbot_manipulation_vision::RotatedRect_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::youbot_manipulation_vision::RotatedRect_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.centerPoint);
    stream.next(m.width);
    stream.next(m.height);
    stream.next(m.angle);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct RotatedRect_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::youbot_manipulation_vision::RotatedRect_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::youbot_manipulation_vision::RotatedRect_<ContainerAllocator> & v) 
  {
    s << indent << "centerPoint: ";
s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.centerPoint);
    s << indent << "width: ";
    Printer<double>::stream(s, indent + "  ", v.width);
    s << indent << "height: ";
    Printer<double>::stream(s, indent + "  ", v.height);
    s << indent << "angle: ";
    Printer<double>::stream(s, indent + "  ", v.angle);
  }
};


} // namespace message_operations
} // namespace ros

#endif // YOUBOT_MANIPULATION_VISION_MESSAGE_ROTATEDRECT_H

