"""autogenerated by genpy from youbot_manipulation_vision/RotatedRect.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class RotatedRect(genpy.Message):
  _md5sum = "85ead10cf1031b0f418b5071f7763172"
  _type = "youbot_manipulation_vision/RotatedRect"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """#Center of the rotated rectangle
geometry_msgs/Point centerPoint

#The width of the rotated rectangle
float64 width
#The height of the rotated rectangle
float64 height

#The angle of the rotated rectangle
float64 angle
================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

"""
  __slots__ = ['centerPoint','width','height','angle']
  _slot_types = ['geometry_msgs/Point','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       centerPoint,width,height,angle

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RotatedRect, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.centerPoint is None:
        self.centerPoint = geometry_msgs.msg.Point()
      if self.width is None:
        self.width = 0.
      if self.height is None:
        self.height = 0.
      if self.angle is None:
        self.angle = 0.
    else:
      self.centerPoint = geometry_msgs.msg.Point()
      self.width = 0.
      self.height = 0.
      self.angle = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_6d.pack(_x.centerPoint.x, _x.centerPoint.y, _x.centerPoint.z, _x.width, _x.height, _x.angle))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.centerPoint is None:
        self.centerPoint = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 48
      (_x.centerPoint.x, _x.centerPoint.y, _x.centerPoint.z, _x.width, _x.height, _x.angle,) = _struct_6d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_6d.pack(_x.centerPoint.x, _x.centerPoint.y, _x.centerPoint.z, _x.width, _x.height, _x.angle))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.centerPoint is None:
        self.centerPoint = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 48
      (_x.centerPoint.x, _x.centerPoint.y, _x.centerPoint.z, _x.width, _x.height, _x.angle,) = _struct_6d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_6d = struct.Struct("<6d")
